name: 2023-07-06-uproot-awkward-columnar-hats
channels:
   - conda-forge
dependencies:
   - awkward<2
   - pyarrow#==8.0.0
   - numpy#==1.21.6
   - scipy#==1.7.3
   - matplotlib#==3.5.2
   - pandas#==1.3.5
   - hist#==2.6.1
   - numba#==0.55.2
   - xrootd#==5.4.3
   - root==6.28*
   - pip==23.1.2
   - pip:
       - uproot==4.3.7
       - particle#==0.23.0
       - vector==1.1.0
