name: 2023-07-06-uproot-awkward-columnar-hats
channels:
   - conda-forge
dependencies:
   - awkward==1.10.3
   - pyarrow==12.0.1
   - numpy==1.24.4
   - scipy==1.11.1
   - matplotlib==3.7.1
   - pandas==2.0.3
   - hist==2.6.3
   - numba==0.57.1
   - xrootd==5.5.4
   - root==6.28*
   - pip==23.1.2
   - pip:
       - uproot==4.3.7
       - particle==0.23.0
       - vector==1.1.0
